### ISSUE TITLE
[XSLT converter] xslt-with-param does not work

### ISSUE THREAD

**Issue by jnehring** [freme-project/basic-services#110]
The XSLT converter xslt-with-param does not work on freme-dev and freme-live.  This CURL

```
curl -X POST -H "Content-Type: text/xml" -H "Cache-Control: no-cache" -H "Postman-Token: 3b4f7b6c-33e6-9506-5a36-7381d5167652" -d '<?xml version="1.0"?>
<note>
    <to>Tove</to>
    <from>Jani</from>
    <heading>Reminder</heading>
    <body>Dont forget me this weekend!</body>
</note>' "http://api-dev.freme-project.eu/current/toolbox/xslt-converter/documents/xslt-with-param?myparam=TEST"
```

produces

```
<?xml version="1.0" encoding="UTF-8"?>TEST
```

**Comment by ArneBinder** [comment]
I think it works fine. When you have a look at [the converter](https://api-dev.freme-project.eu/current/toolbox/xslt-converter/manage/xslt-with-param), just the value of the parameter 'myparam' is printed, which can be set when the user submits a value for it, otherwise it defaults to 'set internally'. In general, this converter was just created to have a (very) simple example to demonstrate the usage of parametrized converters. Perhaps it should be replaced by sth more meaningful.

**Comment by jnehring** [comment]
oh cool. so it is not a bug but a feature. thanks @ArneBinder  :)
