### ISSUE TITLE
[proxy-filter] wrong status code and content length

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/basic-services#37]
In [ProxyServlet.doProxy](https://github.com/freme-project/basic-services/blob/master/filters/proxy-filter/src/main/java/eu/freme/bservices/filter/proxy/ProxyServlet.java#L48): `proxyService.writeProxyToResponse(response, proxy);` does not effectively modify the status code and content length of the response.

**Comment by jnehring** [comment]
The code passage mentioned in [ProxyServlet.doProxy](https://github.com/freme-project/basic-services/blob/master/filters/proxy-filter/src/main/java/eu/freme/bservices/filter/proxy/ProxyServlet.java#L48) does not exist any longer because it was re-written. Also I cannot reproduce this error any longer. So I think the issue was solved by rewriting the code.
